services:
  postgres:
    image: postgres:16-alpine
    container_name: therapy_postgres
    environment:
      POSTGRES_DB: therapy_companion
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - '5433:5432'
    volumes:
      - therapy_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d therapy_companion']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  therapy_pgdata:
